#pragma once

#define RENDERER_VER_MAJOR 0
#define RENDERER_VER_MINOR 1
#define RENDERER_VER_PATCH 0
#define RENDERER_VERSION (RENDERER_VER_MAJOR * 10000 + RENDERER_VER_MINOR * 100 + RENDERER_VER_PATCH)